name: Test release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  test_published:
    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ubuntu-20.04, windows-2019, macos-11]
        node-version: [14.x, 16.x, 18.x]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: npm i -g npm@latest
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp install
      - run: node ./scripts/pympip install --upgrade pip
      - run: node ./scripts/pympip install -r test/requirements.txt
      - name: Run unit tests
        run: npm test
