# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x, 18.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npm i node-gyp
    - run: npm run build
    - run: python3 -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: npm test

  codecov:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install --ignore-scripts
    - run: npm i node-gyp
    - run: npx node-gyp configure --debug --enable_coverage
    - run: npx node-gyp build
    - run: python3 -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: npx c8 npm test
    - run: npm run gcov
    - run: npm run lcov
    - run: npm run codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
