# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build_shared:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-20.04, macos-11, windows-2019]
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --ignore-scripts
      - run: npm run build
      - run: python3 -m pip install --upgrade pip
      - run: pip3 install -r test/requirements.txt
      - run: npm test

  build_static:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-20.04, macos-11]
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: kanga333/variable-mapper@master
        with:
          key: "${{ matrix.platform }}"
          map: |
            {
              "ubuntu-20.04": {
                "static_python": "/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8-pic.a -lexpat"
              },
              "macos-11": {
                "static_python": "libpython3.9.a"
              }
            }
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp configure --static_python=${{ env.static_python }}
      - run: npx @mapbox/node-pre-gyp build
      - run: python3 -m pip install --upgrade pip
      - run: pip3 install -r test/requirements.txt
      - run: npm test

  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install --ignore-scripts
      - run: npx node-pre-gyp configure --debug --enable_coverage
      - run: npx node-pre-gyp build
      - run: python3 -m pip install --upgrade pip
      - run: pip3 install -r test/requirements.txt
      - run: npx c8 npm test
      - run: npm run gcov
      - run: npm run lcov
      - run: npm run codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
