# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  shared_python:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - run: echo LDFLAGS=`python3-config --ldflags --embed` >> $GITHUB_ENV
      - run: echo CFLAGS=`python3-config --cflags --embed` >> $GITHUB_ENV
      - run: gcc ${CFLAGS} python_test.c -o python_test ${LDFLAGS}
      - run: ./python_test
